name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # install dependencies
    - name: boost
      run: sudo apt-get update && sudo apt-get install -yq libboost1.65-dev
    # build project
    - name: mkdir
      run: mkdir build
    - name:  build
      run: make build
